name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: make install

    - name: Install Playwright drivers
      run: |
        go install github.com/playwright-community/playwright-go/cmd/playwright@latest
        playwright install --with-deps

    - name: Verify Playwright installation
      run: playwright --version

    - name: Run tests and generate report
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' make test-report

    - name: Build package
      run: make build