name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: make install
    
    - name: Install Playwright
      run: |
        npm install -D playwright@1.50.1
        npx playwright install

    - name: Run tests and generate report
      run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' make test-report

    - name: Build package
      run: make build
