name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Download Go dependencies
      run: go mod download
        
    - name: Install dependencies
      run: make install
    
    - name: Run tests and generate report
      run: |
            go clean
            rm -f bin/GoLang_FRT_E2E_Tests
            rm -f reports/*
            mkdir -p reports
            go clean -testcache
            go test -v -count=1 ./tests/e2e/home_page_test.go
            go test -v -count=1 ./tests/e2e/sandbox_page_test.go
            go run cmd/generate_report/main.go
            
    - name: Build package
      run: make build
