name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Download Go dependencies
      run: go mod download
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'

    - name: Install dependencies
      run: make install

    
    - name: Install Playwright
      run: |
        npm install -D playwright@latest
        npx playwright install

    - name: Verify Playwright installation
      run: npx playwright --version

    - name: Run tests and generate report
      run: make test-report

    - name: Build package
      run: make build
