name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: make install
    
    - name: Install Playwright
      run: |
        npm install -g playwright@1.50.1

    - name: Run tests 
      run: make test
    
    - name: Run tests and generate report
      run: make test-report

    - name: Build package
      run: make build
